### ISSUE TITLE
does not work with gevent

### ISSUE THREAD

**Issue by Iarwa1n** [Haikson/sitemap-generator#10]
When having gevent installed, this package does not work anymore. I get th following error:

```
/usr/local/lib/python3.6/site-packages/pysitemap/crawler.py:19: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['urllib3.util.ssl_ (/usr/local/lib/python3.6/site-packages/urllib3/util/ssl_.py)', 'urllib3.util (/usr/local/lib/python3.6/site-packages/urllib3/util/__init__.py)'].
  monkey.patch_all()
```

When I manually fix this, by moving the "import requests" command down in crawler.py (see https://github.com/gevent/gevent/issues/1016), My script runs, but only parses the root page of the given URL. This happens with just the example script as given in the README.

**Comment by wirelessfuture** [comment]
Experiencing the same now, does it work without gevent?

**Comment by Haikson** [comment]
Soon I’ll rewrite code without gevent on threads. Just wait please.

**Comment by Haikson** [comment]
New version based on aiohttp and not threads. Thanx for issue reporting
