### ISSUE TITLE
PyPI sdist missing version.py

### ISSUE THREAD

**Issue by jayvdb** [Haikson/sitemap-generator#15]
```py
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from version import VERSION
ModuleNotFoundError: No module named 'version'
```

**Comment by Haikson** [comment]
What version of python are You using?
What command line are you calling?

**Comment by jayvdb** [comment]
https://pypi.org/project/sitemap-generator/#files

`python3 setup.py install`

**Comment by Haikson** [comment]
Try to install newer version (0.9.3)

```
pip3 install sitemap-generator
```
for new installation, or
```
pip3 install sitemap-generator -U
```
for upgrade package

With python3.8 there is no errors

**Comment by jayvdb** [comment]
still the same.

Please download the tarball from https://pypi.org/project/sitemap-generator/#files .  Unpack it.  Install it.  It will fail because it does not have a `version.py` in the tarball.

**Comment by Haikson** [comment]
There no issue.
If You want install from source code, then dounload from github https://github.com/Haikson/sitemap-generator

Installation comand from pypi repository is
```
pip install sitemap-generator

**Comment by jayvdb** [comment]
`pip install sitemap-generator` is using the wheel.

This bug is in the sdist which is uploaded as https://files.pythonhosted.org/packages/37/7b/533126406a2d16b0ce4fabfae92d5fa45574698b278bd2c37b4735940aa0/sitemap-generator-0.9.4.tar.gz

If you dont want to support an sdist, please do not upload one into PyPI
