### ISSUE TITLE
Way of excluding urls?

### ISSUE THREAD

**Issue by graysham** [Haikson/sitemap-generator#16]
Just wondering if with the current code there is a way of excluding urls from the crawl. For example

http://x.com/blah/ is root_url and i want to be able to exclude things like http://x.com/blahs?cxdd which will be the ajax request links.

**Comment by graysham** [comment]
Also if possible a way of excluding links that do not resolve to html files, such as download links etc.

**Comment by graysham** [comment]
I have actually now created my own fork with a exclude urls function.

**Comment by Haikson** [comment]
added a parameter **exclude_urls**
