### ISSUE TITLE
Is there any way to pass headers to aiohttp?

### ISSUE THREAD

**Issue by JonathanLoscalzo** [Haikson/sitemap-generator#19]
The title is fully explained, we need to craw a site but we also need to pass some credentials as headers, such Authorization token. 
Is there any way to do that without reimplementing crawler and Crawler?

Thanks!

**Comment by Haikson** [comment]
For changing headers You can to try set it after Crawler initialization. Only once before calling run() function
There are no other API options to change headers.

```python
import asyncio
import aiohttp
import signal
from pysitemap.base_crawler import Crawler

loop = asyncio.get_event_loop()
c = Crawler(root_url, out_file=out_file, out_format=out_format, maxtasks=maxtasks)
headers={"Authorization": "Basic bG9naW46cGFzcw=="}
c.session = aiohttp.ClientSession(headers=headers)
loop.run_until_complete(c.run())

try:
    loop.add_signal_handler(signal.SIGINT, loop.stop)
except RuntimeError:
    pass
