### ISSUE TITLE
ImportError: No module named 'crawler'

### ISSUE THREAD

**Issue by ghost** [Haikson/sitemap-generator#2]
Steps followed:

    root@hoof:~# pip install sitemap-generator
    Collecting sitemap-generator
      Downloading sitemap-generator-0.3.9.zip
    Collecting beautifulsoup4 (from sitemap-generator)
      Downloading beautifulsoup4-4.5.1-py3-none-any.whl (83kB)
    Collecting mechanize (from sitemap-generator)
      Downloading mechanize-0.2.5.tar.gz (383kB)
    Installing collected packages: beautifulsoup4, mechanize, sitemap-generator
      Running setup.py install for mechanize ... done
      Running setup.py install for sitemap-generator ... done
    Successfully installed beautifulsoup4-4.5.1 mechanize-0.2.5 sitemap-generator-0.3.9
    root@hoof:~# exit

    moses@hoof:~$ pip list |grep sitemap
    sitemap-generator (0.3.9)

    moses@hoof:~$ python -c 'import pysitemap'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.5/dist-packages/pysitemap/__init__.py", line 1, in <module>
        from crawler import Crawler
    ImportError: No module named 'crawler'

Expected outcome: able to type in the example described in README.md  
Seen outcome: ImportError on the first line.

**Comment by Haikson** [comment]
I see you are using python3.5
Unfortunately, the script has only been tested under 2.7

[https://github.com/Haikson/sitemap-generator/blob/master/setup.py#L32](https://github.com/Haikson/sitemap-generator/blob/master/setup.py#L32)
