### ISSUE TITLE
cannot connect to the host

### ISSUE THREAD

**Issue by BoySku** [Haikson/sitemap-generator#22]
i tried to generate sitemap for this website 
but couldn't pass ssl verification any solution to this issue ?

https://cder.dz has error 'Cannot connect to host cder.dz:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify 
failed: Hostname mismatch, certificate is not valid for \'cder.dz\'. (_ssl.c:1124)")]'

**Comment by Haikson** [comment]
try with new version
Now You can use http_request_options dictionary to build kwargs for aiohttp.ClientSession()._request
read in new Readme and try to use http_request_options={"ssl": False}
