### ISSUE TITLE
How to set max limit for the URLs generated

### ISSUE THREAD

**Issue by RajiRai** [Haikson/sitemap-generator#23]
Hi,
I used the code to generate sitemap for a website that has 50k+ pages. However, I want to restrict the crawling to 50K URLs. Does the crawler() support any parameters for this like max_url.
Thanks
Raji

**Comment by Haikson** [comment]
Hi,
Currently, crawler does not support any parameters to limit the number of URLs per file.

I'm not sure that I can implement such functionality in the near future.
