### ISSUE TITLE
Version 0.9.10 directory "parsers" is missing in PyPI

### ISSUE THREAD

**Issue by suraw00t** [Haikson/sitemap-generator#26]
Latest version 0.9.10 in PyPI when install sitemap-generator with pip the directory parsers is missing, plz fix it

**Comment by a8ns** [comment]
it looks like you need to clone this repo and then sudo pip install ./<packagename>. Probably the author haven't configured it properly on PyPi?

**Comment by suraw00t** [comment]
I think the author haven't configured it on setting up file or something.
I have same issue with installing from this repo.
`ModuleNotFoundError: No module named 'pysitemap.parsers'`

and in directory build/lib/pysitemap there is not 'parsers' here.

**Comment by a8ns** [comment]
After figuring it out with pysitemap.parsers by adding the manually I still have an issue: 
RuntimeError: This event loop is already running
I gave up on using this package and gonna try out a different solution.

**Comment by suraw00t** [comment]
I found solution for parsers issues and I created pull request to this repo.
You can see the changes.
For your issue I think you may use set_event_loop() instead get_event_loop() or you could try to run test.py file, I ran it with no any errors.
good luck
