### ISSUE TITLE
Error when page has an xml declaration

### ISSUE THREAD

**Issue by adieyal** [Haikson/sitemap-generator#8]
See this error in line 104
*** ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

Seems to occur when a page has an XML declaration - e.g. www.dsd.gov.za

Doesn't occur when using
                `tree = html.fromstring(response.content)`
instead of
                `tree = html.fromstring(response.text)`

not sure what the right solution is, perhaps
```
try:  
    tree = html.fromstring(response.text) 
except ValueError:
    tree = html.fromstring(response.content)
````

Seems clumsy though

**Comment by Haikson** [comment]
fixed. thanks
